# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - selfregulator

on:
  push:
    branches:
      - prod/be

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      # Build backend
      - name: Build backend
        run: |
          cd backend
          npm install
          npm run build --if-present

      # Zip backend artifact for deployment
      - name: Zip backend artifact
        run: zip backend-release.zip backend/* -r

      # Upload backend artifact for deployment job
      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend-app
          path: backend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      # Download backend artifact from build job
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: backend-app

      # Unzip backend artifact for deployment
      - name: Unzip backend artifact for deployment
        run: unzip backend-release.zip

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E85D517F38C04D0A8B00ADD6F0F92D40 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3424EA59EFA74C68B17B211A8EB091E4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_721D8DEB07A349FA9F08ED456112428D }}

      # Deploy backend to Azure Web App
      - name: Deploy backend to Azure Web App
        id: deploy-backend-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'selfregulator'
          slot-name: 'Production'
          package: ./backend
